# Generated by Django 4.0.3 on 2022-03-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=122)),
                ('password', models.CharField(max_length=122)),
                ('Address', models.CharField(max_length=122)),
                ('Address2', models.CharField(max_length=122)),
                ('mob_num', models.IntegerField(max_length=100)),
                ('city', models.CharField(max_length=122)),
                ('state', models.CharField(max_length=122)),
                ('zip', models.IntegerField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
