# Generated by Django 4.0.3 on 2022-03-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_pdf_alter_contact_mob_num_alter_contact_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='photo',
            field=models.FileField(upload_to='mypdf'),
        ),
    ]
