# Generated by Django 4.0.3 on 2022-03-09 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_pdf_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='photo',
            new_name='pdf',
        ),
    ]
