# Generated by Django 4.0.3 on 2022-03-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_photo_pdf_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='capture')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
