# Generated by Django 4.0.1 on 2022-04-07 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_capture_delete_capture_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Capture',
        ),
    ]
