# Generated by Django 4.0.1 on 2022-04-10 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_delete_capture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pdf',
        ),
    ]
